### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by ritalinn** [quiqupltd/libelection#3]
I am a designer. I want to design as depona voluntarily. Do you want to ?

**Comment by zorbash** [comment]
I'd say that as long as you agree to contribute it under the same license as the source of this repo, go for it!

**Comment by ritalinn** [comment]
It's a little late. I wanted to keep the colors in line with Elixir.

![libelection](https://user-images.githubusercontent.com/41344739/42949343-3708ef0e-8b7a-11e8-8cd2-0e55ca90eec6.jpg)

**Comment by zorbash** [comment]
Colour-wise I'd choose any of the first 2. @IanVaughan wdyt?

**Comment by ritalinn** [comment]
If you like it, I can send you files.

**Comment by IanVaughan** [comment]
Given this version of the Elixir logo :

![https://cdn-images-1.medium.com/max/716/1*wVcT8A29lBkN0gXFPJUF3w.png](https://cdn-images-1.medium.com/max/716/1*wVcT8A29lBkN0gXFPJUF3w.png)

I would vote on the second version.

Many thanks.

**Comment by ritalinn** [comment]
What is your decision?

**Comment by IanVaughan** [comment]
> I would vote on the second version.

Sorry, that meant we choose that second version.

**Comment by ritalinn** [comment]
I sent files. I sent pr.

**Comment by IanVaughan** [comment]
Many thanks

**Comment by IanVaughan** [comment]
https://github.com/quiqupltd/libelection/pull/4
